#cloud-config
users:
  - name: ryan
    groups: [wheel]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: false
    passwd: '$6$tspU12IF1gAnoagy$Wit5znedzH/5UVP2Atqh3b6ZxOdQihjShuiJMKecJwFmm1zElFQLIXSYDJdCTWSmxiAPfjXVwrn7J5mThEnlK0'
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqDX9cCyisQ2R34wJzelFCCfUQEfENEtlSUTjCxFZR/ ryan@ryanrothwell.ca

packages:
  - nginx
  - epel-release
  - policycoreutils-python-utils
  - certbot
  - python3-certbot-nginx

write_files:
  - path: /etc/ssh/sshd_config.d/99-hardened.conf
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      AllowUsers ryan
      PubkeyAcceptedAlgorithms +ssh-rsa,rsa-sha2-256,rsa-sha2-512
  
  - path: /etc/nginx/conf.d/ryanrothwell.ca.conf
    content: |
      server {
          listen 80;
          listen [::]:80;
          server_name ryanrothwell.ca www.ryanrothwell.ca;

          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header Referrer-Policy "no-referrer-when-downgrade" always;

          root /usr/share/nginx/html;
          index index.html;

          location / {
              try_files $uri $uri/ =404;
          }
          
          location ~ /\. {
              deny all;
          }
      }

runcmd:
  - chown -R ryan:ryan /usr/share/nginx/html
  - systemctl restart sshd
  - systemctl enable --now nginx
