name: Deploy Website Updates
on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
  workflow_dispatch:
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Copy Website Files to VM via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ryan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "website/*"
          target: "/usr/share/nginx/html/"
          strip_components: 1
